apiVersion: v1
appVersion: 1.0
description: Letsencrypt Cluster Issuer
name: letsencrypt
version: 1.0.0
maintainers:
  - name: Shyam Jandhyala
    email: jandhyala.shyam@tieto.com
kubeVersion: ">=1.9"